language: python
python:
- "3.7"
os:
- linux

install:
- pip install --upgrade pip setuptools wheel
- pip install -r requirements.txt
- pip install coveralls codecov
- python setup.py sdist bdist_wheel
- pip install tradssat --no-index --find-links=./dist

script:
- rm -r tradssat
- coverage run --rcfile='tests/.coveragerc' -m unittest discover

after_success:
- coveralls --rcfile='tests/.coveragerc'
- codecov
