language: python
python:
- '3.6'
os:
- linux
env:
  global:
  - TX_BRANCH="master"
install:
- pip install --upgrade pip setuptools wheel
- pip install -r requirements.txt
- pip install coveralls codecov codacy-coverage
- pip install transifex-client sphinx sphinx-intl
- python setup.py sdist bdist_wheel
- pip install tradssat --no-index --find-links=./dist
script:
- cd tests
- coverage run -m unittest
after_success:
- coveralls --rcfile=.coveragerc
- codecov
- coverage xml
- python-codacy-coverage -r coverage.xml
- cd ..
- cd docs
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then sh .tx/tx.sh push; sh .tx/tx.sh pull;
  fi
- cd ..
deploy:
  provider: pypi
  user: julien.malard
  password:
    secure: tT6KdULEhevoi2AbRauuVecnogjgKT6iVLNqfRIz7SAwK9+J2tV62aJrOv8hmVzn5vKgSYRXsT/AjFTrIWeYLpQEQLuHLOTVfK/cqnDIwQwoZzWGdLWobYFBo7LS930mxMxCNJHQQL9jR5G4jgpxX9ANpfC7u7nUeotjHp8BYcx+C/gysVgI7IJdHIuogwXJHn1UW10qY/f2ToADfgA9uCgZuCgsbLmq+WA7/Ae47VAUVjg3p5xhscaYUIF+FDlt3tq13umnqujvMoqv0bDNCfE5jY2TXvqPzxJ9E6S7oh7M/YPUd8osSwjYGxtjDVeqj8fYIuC8vCwn6B9LVuE/MyYVdjPtLAnHrLjJPxclr686gloRV9xrvVGFfPjOnG1TSYKX/dZg4G+Nmz32XqK4Rc/wrdOP2tWfvkmAV34bZpuJfzKQzquc48cXWiJ91DcjyqGaTIv4WRSnS3TryzO61lMwRm4yiHKbXxrFyHvreAIREqJGgs7T/gYVcncTeIwvqPkakfXXiCL9SBBlHWDUu/lA2C4zvk3TW23NlA8kivNqsk1Vpkv3aKpxDBcW9AUUwu+GvwUXOhdcE8Cy0u3QHl7Pnk3DAmPMvSQPqtFi6/59c+laQvqFZ9POLMJ6HjckvTEKls0h7GzWlr4zxZieIcetKfJCSI66jkGDgHIy93s=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
