language: python
python:
- '3.7'
- '3.8'
os:
- linux
env:
  global:
  - TX_BRANCH="master"

install:
  - pip install poetry
  - pip install coveralls codecov
  - poetry install -v

script:
  - poetry run pytest --cov=\"src\"

after_success:
- coveralls --rcfile=.coveragerc
- codecov
- coverage xml
- python-codacy-coverage -r coverage.xml
- cd ..
- cd docs
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then sh .tx/tx.sh push; sh .tx/tx.sh pull;
  fi
- cd ..
deploy:
  provider: pypi
  user: julien.malard
  password:
    secure: Ow/K4VoeIsC3kbdoYnxCSwQjFK3aqGTyev0Oo1pMc17BlOht0YbQmcBgoQA15cWLq1FE8VUz1cHnWgwsdzQK/UtZgp53kHXdQ0+avaCZ/y2QRHGOymle0XoUGK4ea/EIvWxtJHDnjyqJSgPXrpGu3lcQ6uw1N+UtTBweNlwMfhXpMjiQStZ2Xbxa5ZGlVVuY8Ei7XEg27dgoxeQzSkhEGMRHoWIos3i3Wae85w+o+Rt6S625RAiqMJW8wBSrtzIiMleMemYweD6LrIbCEOdTqAlcRF5TZaRLtL1Zvd7RL7AZvcwTqlAfXeWLN7bHl6jOpMNrWOYDv6doPZdmowzlMXJWYE9o4ZkF5VTwDPE+uAmXXlFsu0kfEoJK4hyl0PnAoGC4iAgSPGdw3kAQEz0WHl33sP7m6KxhYMASBCnSIkebngeTBTZiTpgHB/3i/NQmjLYThPf/jD9cwIqVeHgFqp+XpUoe7zzo8RM69Yeoz9oErrFnKi4m4F9DQWiadBLZFcO7Qtx86UVQtPS7jHJ9n/sa+lAmOjWmcRRrWvkEFTtb0SsfQXJp65jatR1FvrC2q1SBYMNCl/EMOmS4Hc/OGgv6/K+dTRAU9tKUciYeNbIrbNCVBen+SApt5UlOLE7ASVUnRj20Uh2VgBFPXGZ0jSFNNTaiEWbvxv63qHbuKSw=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
