language: python
python:
- '3.6'
os:
- linux
env:
  global:
  - TX_BRANCH="master"
install:
- pip install --upgrade pip setuptools wheel
- pip install -r requirements.txt
- pip install coveralls codecov codacy-coverage
- pip install transifex-client sphinx sphinx-intl
- python setup.py sdist bdist_wheel
- pip install tradssat --no-index --find-links=./dist
script:
- cd tests
- coverage run -m unittest
after_success:
- coveralls --rcfile=.coveragerc
- codecov
- coverage xml
- python-codacy-coverage -r coverage.xml
- cd ..
- cd docs
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then sh .tx/tx.sh push; sh .tx/tx.sh pull;
  fi
- cd ..
deploy:
  provider: pypi
  user: julien.malard
  password:
    secure: KlPzyZNoUV+V3GSWE49ld2zEKtmumox9G0uNMgj0bgBmyLagws7oDIXUnhBKlIYEK5tG6GAZUGKXg58dBRXkaBatuBC6WKsuUa4HyZgW5hPwlUB141HZafz+MElgpty2FiPDeuznCm+jhu0XnRGuejPsKgkrdoamPlPCzIGquMmAIh5mN7v7IpcYlkA9a8UExEfie2dQteAkFoZPJ/f/KNCnUwmTNJZk+uykjCk9na2XQxgVFnVdG5xLnUY0rxB/+s7nteywG2uOtohOD/aWPRJ7rolN57+lcemQ9RCLL1+8jPRjug1oiUO8QU3o8KZJOdnCkW6rK3YYHydrrGyUxL7KZAgHQAGE0wz6P9z20QLJ2HdbwuaEBC1E1QVlfVl3xXDWC634bJDTEyDCBsWOGOplve2h9oXXZ/nkGCCtbbhDYhfcMTy4S8TjQfpvYlbS1cekGz4JoAAY9NMknsq6IhXceO++CLMCW8k8T0UaToZpxe6I1Q70WTQnMtRzoQOKIKdCzIYAgyQ3Z6FDpBQhYYwxfRBN8sePYqMSd01dmdvEkF/wBPTpDlOvvt0XHnee3LkeNoU8HNn+t3P6DSEiCaRLESN5h7G/1q6hda+FIa03cF6svJUXo+cqMqL13Vcu1EBP07gT8uwfoUFHBzUX7rRpfEZ7fxBa/W1iGOZL9bk=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
